export const ADD_NEW_POST = "ADD_NEW_POST";
export const WRITE_NEW_MESSAGE = "WRITE_NEW_MESSAGE";
export const CHANGE_PROFILE_STATUS = "CHANGE_PROFILE_STATUS";

export const BROWSE_USERS = "BROWSE_USERS";
export const BTN_LOADER = "BTN_LOADER";
export const FETCH_USERS_LOADED = "FETCH_USERS_LOADED";
export const FETCH_USER_BY_ID = "FETCH_USER_BY_ID";
export const CHANGE_USER_STATUS = "CHANGE_USER_STATUS";
export const LOAD_MORE_USERS = "LOAD_MORE_USERS";
export const FOLLOW_HANDLER = "FOLLOW_HANDLER";

export const LOG_IN_USER = "LOG_IN_USER";
export const LOG_OUT_USER = "LOG_OUT_USER";
export const INSERT_LOGGED_USER = "INSERT_LOGGED_USER";
export const THROW_AUTH_EXCEPTION = "THROW_AUTH_EXCEPTION";
